const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Olyvar',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner4.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner5.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 70,
      brand: 'Olyvar',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 70,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A Popular Shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
  ],
};
export default data;
